#!/usr/bin/env bash
folder="/home/potato/Desktop/Memory"
bochsFolder="/home/potato/Desktop/Bochs Folder"
src="$folder/src"
bin="$folder/bin"
cd "$folder"
nasm -f bin "$src/memory.asm" -l memory.lst -o "$bin/memory"
sudo dd if="$bin/memory" of="$bochsFolder/test.iso" bs=512 count=1 | hexdump -C
sudo chmod u=rwx,g=rwx,o=rwx "$bochsFolder/test.iso"
cd "$bochsFolder"
bochs
$SHELL
